apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ExternalName
  externalName: aurora-cluster-threedots-instance.cohgn7ym7gy1.ap-south-1.rds.amazonaws.com

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ExternalName
  externalName: elasticache-redis-k2cloud.oqjqgm.ng.0001.aps1.cache.amazonaws.com

---
apiVersion: v1
kind: Service
metadata:
  name: jarvis-service
spec:
  selector:
    app: jarvis
  type: ClusterIP
  ports:
    - name: java
      protocol: TCP
      port: 8080
      targetPort: 8080