apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql_datasource_username: {{ .Values.secrets.mysql_datasource_username }}
  mysql_datasource_password: {{ .Values.secrets.mysql_datasource_password }}
  stream_api_secret: {{ .Values.secrets.stream_api_secret }}
  webengage_api_key: {{ .Values.secrets.webengage_api_key }}
  vault_token: {{ .Values.secrets.vault_token }}
  vision_token: {{ .Values.secrets.vision_token }}
  valkyrie_token: {{ .Values.secrets.valkyrie_token }}
  bifrost_token: {{ .Values.secrets.bifrost_token }}
