apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} 
  namespace: {{ .Values.namespace }} 
spec:
  selector:
    app: {{ .Values.deployment.name }} 
  type: ClusterIP 
  ports:
    - name: {{ .Values.service.portName }}
      protocol: {{ .Values.service.protocol }} 
      port:  {{ .Values.service.port }} 
      targetPort: {{ .Values.deployment.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-jarvis-service
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.service.mysql }}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-jarvis-service
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.service.redis }}
