apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name }}
  namespace: {{ .Values.namespace }}
spec:
  awsName: {{ .Values.virtualservice.awsName }}
  provider:
    virtualNode:
      virtualNodeRef:
        name: {{ .Values.virtualnode.name }}
